package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VerboseLevel
// +kubebuilder:validation:Enum=Disable;Enable;Moar;Extreme
type VerboseLevel string

const (
	// Disable no verbose output at all
	Disable VerboseLevel = "Disable"

	// Enable print errors and warnings
	Enable VerboseLevel = "Enable"

	// Moar print client commands and responses
	Moar VerboseLevel = "Moar"

	// Extreme print internal state transactions
	Extreme VerboseLevel = "Extreme"
)

// DockerImage struct for storing image and tag for docker image
type DockerImage struct {
	Name string `json:"name"`
	Tag  string `json:"tag"`
}

type ProxyConfig struct {
	// Listen the listening address and port (name:port or ip:port) for this server pool, default 0.0.0.0:11211
	// +optional
	Listen string `json:"listen"`
	// Hash the name of the hash function, default fnv1a_64
	// +optional
	Hash string `json:"hash"`
	// Hash the key distribution mode for choosing backend servers based on the computed hash value, default ketama
	// +optional
	Distribution string `json:"distribution"`
	// AutoEjectHosts boolean value that controls if server should be ejected temporarily when it fails consecutively server_failure_limit times, default false
	// +optional
	AutoEjectHosts bool `json:"auto_eject_hosts"`
	// number of consecutive failures on a server that would lead to it being temporarily ejected when auto_eject_hosts is set to true, default 2
	// +optional
	ServerFailureLimit int64 `json:"server_failure_limit"`
	// ServerRetryTimeout timeout value in msec to wait for before retrying on a temporarily ejected server, when auto_eject_hosts is set to true, default 30000
	// +optional
	ServerRetryTimeout int64 `json:"server_retry_timeout"`
	// Timeout value in msec that we wait for to establish a connection to the server or receive a response from a server, default 400
	// +optional
	Timeout int64 `json:"timeout"`
	// Servers list of server address, port and weight (name:port:weight or ip:port:weight), default []
	// +optional
	Servers []string `json:"servers"`
}

// Prox struct for enabling and configure Twemproxy
type Twemproxy struct {
	// +optional
	Enable bool `json:"enable"`
	// Size defines the number of Twemproxy instances
	// +kubebuilder:validation:Minimum=1
	// +optional
	Replicas int64 `json:"replicas"`
	// +optional
	Config ProxyConfig `json:"config"`
}

// ===============================================================================
// MemcachedSpec defines the desired state of Memcached
type MemcachedSpec struct {
	// Size defines the number of Memcached instances
	// +kubebuilder:validation:Minimum=1
	Size int32 `json:"size,omitempty"`

	// Port defines the port that will be used to init the container with the image
	ContainerPort int32 `json:"containerPort,omitempty"`

	// This tells the controller to use or not Twemproxy.
	// if config is not set then it will be autogenerated generated
	// +optional
	Proxy Twemproxy `json:"proxy,omitempty"`

	// Parameter for setting image and tag for memcached pod
	// default 'memcached:1.6.23-alpine'
	// +optional
	Image DockerImage `json:"image"`

	// Specifies the verbose level.
	// Valid values are:
	// - "Disable": no verbose output at all;
	// - "Enable"(default): print errors and warnings;
	// - "Moar": print client commands and responses;
	// - "Extreme": print internal state transactions;
	// +optional
	Verbose VerboseLevel `json:"verbose,omitempty"`

	// Resources defines CPU and memory for Memcached prods
	*Resources `json:"resources,omitempty"`
}

// MemcachedStatus defines the observed state of Memcached
type MemcachedStatus struct {
	// Represents the observations of a Memcached's current state.
	Conditions []metav1.Condition `json:"conditions,omitempty" patchStrategy:"merge" patchMergeKey:"type" protobuf:"bytes,1,rep,name=conditions"`
}

// ===============================================================================
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// Memcached is the Schema for the memcacheds API
type Memcached struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MemcachedSpec   `json:"spec,omitempty"`
	Status MemcachedStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MemcachedList contains a list of Memcached
type MemcachedList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Memcached `json:"items"`
}

// ===============================================================================
func init() {
	SchemeBuilder.Register(&Memcached{}, &MemcachedList{})
}
