---
apiVersion: cache.bsod.io/v1
kind: Memcached
metadata:
  name: memcached-sample
spec:
  size: 1

  containerPort: 11211

  verbose: Moar

  proxy:
    replicas: 1
    config:
      listen: 0.0.0.0:11211

  image:
    name: memcached
    tag: 1.6.24

  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
